"""
Create TODOs Node — break a complex task into a structured TODO list.

Uses LLM with Pydantic-validated structured output for reliable JSON
parsing. Converts items to TodoItem format and caps the count.
"""

from __future__ import annotations

import json
from logging import getLogger
from typing import Any, Dict, List

from langchain_core.messages import HumanMessage

from service.langgraph.state import TodoItem, TodoStatus
from service.prompt.sections import AutonomousPrompts
from service.workflow.nodes._helpers import MAX_TODO_ITEMS, safe_format
from service.workflow.nodes.base import (
    BaseNode,
    ExecutionContext,
    NodeParameter,
    register_node,
)
from service.workflow.workflow_state import NodeStateUsage
from service.workflow.nodes.i18n import CREATE_TODOS_I18N

logger = getLogger(__name__)


@register_node
class CreateTodosNode(BaseNode):
    """Break a complex task into a structured TODO list (hard path).

    Generalised: Configurable output field names, max items, and
    JSON parsing behaviour.
    """

    node_type = "create_todos"
    label = "Create TODOs"
    description = "Breaks a complex task into a structured JSON TODO list via LLM. Uses Pydantic-validated structured output for reliable parsing. Converts items to TodoItem format with id/title/description/status/result, and caps the count to prevent runaway execution."
    category = "task"
    icon = "list-todo"
    color = "#ef4444"
    i18n = CREATE_TODOS_I18N
    state_usage = NodeStateUsage(
        reads=["input"],
        writes=["messages", "last_output", "current_step"],
        config_dynamic_writes={
            "output_list_field": "todos",
            "output_index_field": "current_todo_index",
        },
    )

    from service.workflow.nodes.structured_output import (
        CreateTodosOutput, build_frontend_schema as _build_schema,
    )
    structured_output_schema = _build_schema(
        CreateTodosOutput,
        description="Structured TODO list generated by LLM for complex task decomposition.",
    )

    parameters = [
        NodeParameter(
            name="prompt_template",
            label="Prompt Template",
            type="prompt_template",
            default=AutonomousPrompts.create_todos(),
            description="Prompt template for generating the TODO list.",
            group="prompt",
        ),
        NodeParameter(
            name="max_todos",
            label="Max TODO Items",
            type="number",
            default=20,
            min=1,
            max=50,
            description="Maximum number of TODO items to prevent runaway execution.",
            group="behavior",
        ),
        NodeParameter(
            name="output_list_field",
            label="Output List Field",
            type="string",
            default="todos",
            description="State field to store the generated list in.",
            group="state_fields",
        ),
        NodeParameter(
            name="output_index_field",
            label="Output Index Field",
            type="string",
            default="current_todo_index",
            description="State field for the current index (reset to 0).",
            group="state_fields",
        ),
    ]

    async def execute(
        self,
        state: Dict[str, Any],
        context: ExecutionContext,
        config: Dict[str, Any],
    ) -> Dict[str, Any]:
        input_text = state.get("input", "")
        template = config.get("prompt_template", AutonomousPrompts.create_todos())
        max_todos = int(config.get("max_todos", MAX_TODO_ITEMS))
        list_field = config.get("output_list_field", "todos")
        index_field = config.get("output_index_field", "current_todo_index")

        try:
            from service.workflow.nodes.structured_output import CreateTodosOutput

            prompt = safe_format(template, {**state, "input": input_text})
            messages = [HumanMessage(content=prompt)]

            # ── Structured output: schema-validated TODO list ──
            parsed, fallback = await context.resilient_structured_invoke(
                messages,
                "create_todos",
                CreateTodosOutput,
                extra_instruction=(
                    "Each TODO item MUST have 'id' (integer), 'title' (string), "
                    "and 'description' (string). Return between 1 and "
                    f"{max_todos} items."
                ),
            )

            todos: List[TodoItem] = []
            for item in parsed.todos:
                todos.append({
                    "id": item.id,
                    "title": item.title,
                    "description": item.description,
                    "status": TodoStatus.PENDING,
                    "result": None,
                })

            if len(todos) > max_todos:
                todos = todos[:max_todos]

            if not todos:
                logger.warning(
                    f"[{context.session_id}] create_todos: structured output "
                    f"returned empty list, using single-item fallback"
                )
                todos = [{
                    "id": 1,
                    "title": "Execute task",
                    "description": input_text,
                    "status": TodoStatus.PENDING,
                    "result": None,
                }]

            logger.info(f"[{context.session_id}] create_todos: {len(todos)} items")

            result: Dict[str, Any] = {
                list_field: todos,
                index_field: 0,
                "messages": [HumanMessage(content=f"Created {len(todos)} TODO items")],
                "last_output": json.dumps([
                    {"id": t["id"], "title": t["title"]} for t in todos
                ]),
                "current_step": "todos_created",
            }
            result.update(fallback)
            return result

        except Exception as e:
            logger.exception(f"[{context.session_id}] create_todos error: {e}")
            return {"error": str(e), "is_complete": True}
