"""
SudoModel — Mock LLM that produces valid responses for graph testing.

Replaces ``ClaudeCLIChatModel`` in the ``ExecutionContext``.  When a
workflow node calls ``context.resilient_invoke(messages, node_name)``,
the model inspects the node name and message content to determine what
kind of response is expected, then returns an appropriate mock.

For structured-output nodes (classify, review, etc.) the model
generates valid JSON matching the expected Pydantic schema so that
``resilient_structured_invoke`` can parse it successfully.

Design principles:
    • Zero external dependencies — no network, no Claude CLI, no API keys
    • Deterministic by default — same seed → same run
    • Configurable — callers can override default responses per node
"""

from __future__ import annotations

import json
import random
import time
from logging import getLogger
from typing import Any, Dict, List, Optional

from langchain_core.messages import AIMessage
from langchain_core.outputs import ChatGeneration, ChatResult

logger = getLogger(__name__)


# ============================================================================
# Default mock response generators (keyed by node_name hint)
# ============================================================================

_DEFAULT_CATEGORIES = ["easy", "medium", "hard"]
_DEFAULT_VERDICTS = ["approved", "retry"]
_LOREM = (
    "This is a mock response generated by SudoModel for graph testing purposes. "
    "No actual LLM was invoked. The workflow graph is being validated to ensure "
    "all nodes execute correctly and all routing decisions produce valid paths."
)


def _mock_classify(categories: List[str], rng: random.Random) -> str:
    """Generate a valid ClassifyOutput JSON string."""
    cat = rng.choice(categories) if categories else "easy"
    return json.dumps({
        "classification": cat,
        "confidence": rng.choice(["low", "medium", "high"]),
        "reasoning": f"[sudo] Randomly selected '{cat}' for testing.",
    })


def _mock_review(verdicts: List[str], rng: random.Random) -> str:
    """Generate a valid ReviewOutput JSON string."""
    verdict = rng.choice(verdicts) if verdicts else "approved"
    return json.dumps({
        "verdict": verdict,
        "feedback": f"[sudo] Mock review verdict: {verdict}.",
        "issues": [],
    })


def _mock_memory_gate(rng: random.Random) -> str:
    """Generate a valid MemoryGateOutput JSON string."""
    return json.dumps({
        "needs_memory": rng.choice([True, False]),
        "reasoning": "[sudo] Mock memory gate decision.",
    })


def _mock_relevance(rng: random.Random) -> str:
    """Generate a valid RelevanceOutput JSON string."""
    return json.dumps({
        "relevant": True,
        "reasoning": "[sudo] Mock relevance — always relevant in sudo mode.",
    })


def _mock_create_todos(rng: random.Random) -> str:
    """Generate a valid CreateTodosOutput JSON string."""
    count = rng.randint(2, 4)
    todos = [
        {"id": i + 1, "title": f"Todo item {i + 1}", "description": f"[sudo] Mock task {i + 1}"}
        for i in range(count)
    ]
    return json.dumps({"todos": todos})


def _mock_final_review(rng: random.Random) -> str:
    """Generate a valid FinalReviewOutput JSON string."""
    return json.dumps({
        "overall_quality": rng.choice(["excellent", "good"]),
        "completed_summary": "[sudo] All mock tasks completed successfully.",
        "issues_found": [],
        "recommendations": "[sudo] No recommendations — this is a test run.",
    })


def _mock_text_response(node_name: str) -> str:
    """Generate a plain-text mock response for non-structured nodes."""
    return f"[sudo:{node_name}] {_LOREM}"


# ============================================================================
# Node-name → structured schema detector
# ============================================================================

# Maps known node_name prefixes to mock generators.
# The node_name passed to resilient_invoke / resilient_structured_invoke
# is a string like "llm_call", "adaptive_classify", "relevance_gate", etc.

_STRUCTURED_GENERATORS = {
    "classify": "classify",
    "adaptive_classify": "classify",
    "relevance_gate": "relevance",
    "memory_gate": "memory_gate",
    "review": "review",
    "create_todos": "create_todos",
    "final_review": "final_review",
}


class SudoModel:
    """Mock LLM model that produces deterministic fake responses.

    Drop-in replacement for ``ClaudeCLIChatModel`` in the
    ``ExecutionContext``.  Supports both ``ainvoke(messages)``
    (used by ``resilient_invoke``) and ``agenerate(messages)``
    (the LangChain BaseChatModel contract).

    Args:
        seed:         Random seed for reproducibility.
        overrides:    Per-node response overrides.
                      ``{"classify": "easy"}`` forces classify to
                      always return "easy".
        categories:   Categories for classify nodes (default: easy/medium/hard).
        verdicts:     Verdicts for review nodes (default: approved/retry).
        latency_ms:   Simulated latency per call (0 = instant).
    """

    def __init__(
        self,
        *,
        seed: int = 42,
        overrides: Optional[Dict[str, str]] = None,
        categories: Optional[List[str]] = None,
        verdicts: Optional[List[str]] = None,
        latency_ms: int = 0,
    ) -> None:
        self._rng = random.Random(seed)
        self._overrides = overrides or {}
        self._categories = categories or list(_DEFAULT_CATEGORIES)
        self._verdicts = verdicts or list(_DEFAULT_VERDICTS)
        self._latency_ms = latency_ms
        self._call_count = 0
        self._call_log: List[Dict[str, Any]] = []

    # ── Public API (matches ClaudeCLIChatModel) ──

    async def ainvoke(self, messages: list, **kwargs: Any) -> AIMessage:
        """Main entry point called by ExecutionContext.resilient_invoke."""
        self._call_count += 1

        # Detect node_name from message hints
        node_name = self._detect_node_name(messages)
        content = self._generate_response(node_name, messages)

        if self._latency_ms > 0:
            import asyncio
            await asyncio.sleep(self._latency_ms / 1000.0)

        # Build AIMessage with mock cost
        mock_cost = round(self._rng.uniform(0.001, 0.01), 6)
        msg = AIMessage(
            content=content,
            additional_kwargs={
                "cost_usd": mock_cost,
                "duration_ms": self._latency_ms or 1,
                "execution_count": self._call_count,
                "session_id": "sudo-session",
                "conversation_id": "sudo-conv",
            },
        )

        self._call_log.append({
            "call_number": self._call_count,
            "node_name": node_name,
            "response_preview": content[:120],
            "mock_cost": mock_cost,
        })

        logger.debug(
            f"[sudo] Call #{self._call_count} node={node_name} "
            f"response_len={len(content)}"
        )
        return msg

    async def agenerate(self, messages: list, **kwargs: Any) -> ChatResult:
        """LangChain BaseChatModel contract (not typically called directly)."""
        msg = await self.ainvoke(messages, **kwargs)
        return ChatResult(generations=[ChatGeneration(message=msg)])

    # ── Introspection ──

    @property
    def call_count(self) -> int:
        return self._call_count

    @property
    def call_log(self) -> List[Dict[str, Any]]:
        return list(self._call_log)

    # ── Internal ──

    def _detect_node_name(self, messages: list) -> str:
        """Infer the node name from message content heuristics.

        The actual node_name is passed as a parameter to
        ``resilient_invoke`` / ``resilient_structured_invoke``,
        NOT to ``model.ainvoke()``.  Since we only see messages,
        we scan for schema hints or known keywords.

        When used via SudoExecutionContext (which intercepts at
        the resilient_invoke level), this is only a fallback.
        """
        if not messages:
            return "unknown"

        last_content = ""
        for m in reversed(messages):
            if hasattr(m, "content") and m.content:
                last_content = m.content
                break

        lc = last_content.lower()

        # Check for JSON schema instructions (injected by resilient_structured_invoke)
        if '"classification"' in lc:
            return "classify"
        if '"verdict"' in lc:
            return "review"
        if '"needs_memory"' in lc:
            return "memory_gate"
        if '"relevant"' in lc:
            return "relevance"
        if '"todos"' in lc:
            return "create_todos"
        if '"overall_quality"' in lc:
            return "final_review"
        if "yes or no" in lc:
            return "relevance_fallback"

        return "generic"

    def _generate_response(self, node_name: str, messages: list) -> str:
        """Generate the mock response content for a detected node type."""
        # Check user overrides first
        if node_name in self._overrides:
            override = self._overrides[node_name]
            # If it looks like JSON, return as-is
            if override.strip().startswith("{"):
                return override
            # Otherwise, try to build a structured response with the override value
            if node_name in ("classify", "adaptive_classify"):
                return json.dumps({
                    "classification": override,
                    "confidence": "high",
                    "reasoning": f"[sudo] Override: {override}",
                })
            if node_name == "review":
                return json.dumps({
                    "verdict": override,
                    "feedback": f"[sudo] Override verdict: {override}",
                })
            return override

        # Schema-aware generation
        schema_type = _STRUCTURED_GENERATORS.get(node_name)

        if schema_type == "classify":
            return _mock_classify(self._categories, self._rng)
        if schema_type == "relevance":
            return _mock_relevance(self._rng)
        if schema_type == "memory_gate":
            return _mock_memory_gate(self._rng)
        if schema_type == "review":
            return _mock_review(self._verdicts, self._rng)
        if schema_type == "create_todos":
            return _mock_create_todos(self._rng)
        if schema_type == "final_review":
            return _mock_final_review(self._rng)

        # Relevance fallback (YES/NO text)
        if node_name == "relevance_fallback":
            return "YES"

        return _mock_text_response(node_name)
