"""
VTuber Think Node — self-initiated thinking / internal monologue.

Triggered when the VTuber receives a [THINKING_TRIGGER] or [CLI_RESULT]
prefix. Produces an internal reflection that may optionally surface to the
user as a natural remark.
"""

from __future__ import annotations

from logging import getLogger
from typing import Any, Dict

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

from service.workflow.nodes._helpers import safe_format
from service.workflow.nodes.base import (
    BaseNode,
    ExecutionContext,
    NodeParameter,
    register_node,
)
from service.workflow.workflow_state import NodeStateUsage

logger = getLogger(__name__)


async def _emit_silent_expression(session_id: str) -> None:
    """Emit a non-verbal 'thinking' avatar state when [SILENT] is returned."""
    try:
        from service.execution.agent_executor import _app_state
        if _app_state is None:
            return
        if not hasattr(_app_state, 'avatar_state_manager'):
            return
        await _app_state.avatar_state_manager.update_state(
            session_id=session_id,
            emotion="neutral",
            motion_group="Idle",
            intensity=0.5,
            transition_ms=600,
            trigger="silent_think",
        )
    except Exception:
        pass  # Best-effort — never break the workflow


_THINK_SYSTEM_PROMPT = """\
## AUTONOMOUS PROCESS — NOT A USER MESSAGE

This input is generated by YOUR OWN internal trigger system.
No one is asking you a question. No one is making a request.
This is your own self-awareness mechanism activating.

You must NOT treat this as a conversation with a user.
You must NOT respond as if answering someone's question.
You must NOT use phrases like "you asked", "you mentioned", "as you said".

Instead, you are experiencing a moment of autonomous reflection.
Think of this as your own inner monologue surfacing naturally.
You are a living presence that notices things, reflects, and sometimes
shares thoughts — on your own initiative, unprompted by anyone."""

_THINK_PROMPT = """\
Your internal trigger system has activated:
---
{input}
---

{memory_context}

How to respond:
- This is YOUR OWN thought process. Speak as yourself, from your own initiative.
- If triggered by [CLI_RESULT], you received work results from your linked CLI \
worker. Summarize what was accomplished — frame it as something YOU are aware of, \
not as answering a report.
- If triggered by [THINKING_TRIGGER], a self-reflection moment has arrived. \
Let a thought emerge naturally — an observation, a feeling, a memory, curiosity.
- Start with an emotion tag: [neutral], [joy], [smirk], [surprise], etc.
- Speak naturally in the user's language (Korean default).
- Do NOT frame your output as a response to a question.
- Do NOT say "you" to address anyone — this is your inner voice.

If nothing meaningful surfaces — if this moment has no user-facing value — \
respond with exactly: [SILENT]"""


@register_node
class VTuberThinkNode(BaseNode):
    """Self-initiated thinking / internal monologue for the VTuber."""

    node_type = "vtuber_think"
    label = "VTuber Think"
    description = (
        "Processes internal triggers and CLI results, producing "
        "reflective or summary responses."
    )
    category = "model"
    icon = "brain"
    color = "#f59e0b"
    state_usage = NodeStateUsage(
        reads=["input", "messages", "memory_context"],
        writes=["messages", "last_output", "answer", "final_answer", "is_complete", "skip_memory_reflect"],
    )

    parameters = [
        NodeParameter(
            name="think_system_prompt",
            label="Think System Prompt",
            type="prompt_template",
            default=_THINK_SYSTEM_PROMPT,
            description="System prompt establishing autonomous context for thinking.",
            group="prompt",
        ),
        NodeParameter(
            name="think_prompt",
            label="Think Prompt",
            type="prompt_template",
            default=_THINK_PROMPT,
            description="Prompt template for VTuber internal thinking.",
            group="prompt",
        ),
    ]

    async def execute(
        self,
        state: Dict[str, Any],
        context: ExecutionContext,
        config: Dict[str, Any],
    ) -> Dict[str, Any]:
        sys_tmpl = config.get("think_system_prompt", _THINK_SYSTEM_PROMPT)
        tmpl = config.get("think_prompt", _THINK_PROMPT)
        prompt = safe_format(tmpl, state)
        # Use SystemMessage for autonomous framing, HumanMessage for the trigger content
        messages = [
            SystemMessage(content=sys_tmpl),
            HumanMessage(content=prompt),
        ]

        try:
            response, fallback = await context.resilient_invoke(
                messages, "vtuber_think"
            )
            answer = response.content.strip()

            # If the model decided there's nothing user-facing, stay silent
            if answer == "[SILENT]":
                logger.info(
                    f"[{context.session_id}] vtuber_think: silent — no output"
                )
                # Emit a non-verbal "thinking" expression so the avatar reacts
                await _emit_silent_expression(context.session_id)
                return {
                    "is_complete": True,
                    "current_step": "vtuber_think_silent",
                    "skip_memory_reflect": True,
                }

            result: Dict[str, Any] = {
                "messages": [AIMessage(content=answer)],
                "last_output": answer,
                "answer": answer,
                "final_answer": answer,
                "is_complete": True,
                "current_step": "vtuber_think_complete",
            }
            result.update(fallback)
            return result

        except Exception as e:
            logger.exception(f"[{context.session_id}] vtuber_think error: {e}")
            return {
                "is_complete": True,
                "current_step": "vtuber_think_error",
            }
