"""GenyCloud — the user's cloud storage, one level ABOVE agents."""

from service.cloud.store import (
    CLOUD_SCOPE_ID,
    RESERVED_CLOUD_NAMES,
    cloud_notify_key,
    cloud_storage_path,
    cloud_workspace,
    connected_sessions,
    adopt_agent_space,
    agent_gapt_space,
    agent_space,
    agents_root,
    cloud_relative,
    ensure_agent_space,
    forget_device,
    is_cloud_scope,
    is_connected,
    known_devices,
    remember_device,
    owning_storage,
    release_agent_space,
    user_gapt_root,
    set_connected,
)

__all__ = [
    "CLOUD_SCOPE_ID",
    "RESERVED_CLOUD_NAMES",
    "cloud_notify_key",
    "cloud_storage_path",
    "cloud_workspace",
    "connected_sessions",
    "adopt_agent_space",
    "agent_gapt_space",
    "agent_space",
    "agents_root",
    "cloud_relative",
    "ensure_agent_space",
    "forget_device",
    "is_cloud_scope",
    "is_connected",
    "known_devices",
    "remember_device",
    "owning_storage",
    "release_agent_space",
    "user_gapt_root",
    "set_connected",
]
